# Generated by Django 5.2.8 on 2025-11-10 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.TextField(help_text='Full address including street and area'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contact_info',
            field=models.CharField(help_text='Only 9 digits. +353 will be added automatically.', max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid 9-digit Irish mobile number (e.g., 871234567)', regex='^\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: Add details about the property'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, help_text='Enter rent in euros (e.g., 1200.00)', max_digits=10),
        ),
    ]
